version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /custom/(.*)
  static_files: custom/\1
  upload: custom/.*

- url: /pages/(.*)
  static_files: pages/\1
  upload: pages/.*

- url: /app.js
  static_files: app.js
  upload: app.js

- url: /favicon.ico
  static_files: theme.css
  upload: theme.css

- url: /bower_components/(.*)
  static_files: bower_components/\1
  upload: bower_components/.*

- url: /service/(.*)
  static_files: service/\1
  upload: service/.*

- url: /api/(.*)
  static_files: api/\1
  upload: api/.*

- url: /images/(.*)
  static_files: images/\1
  upload: images/.*

- url: /icons/(.*)
  static_files: icons/\1
  upload: icons/.*

skip_files:
- ^(.*/)?node_modules/.*